# Generated by Django 2.1.7 on 2019-06-11 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nested_example", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="nested_example.User",
            ),
        ),
    ]
