# Generated by Django 2.1.4 on 2019-02-26 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nested_example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to='nested_example.Employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to='nested_example.Role')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='employees',
            field=models.ManyToManyField(related_name='roles', through='nested_example.EmployeeRole', to='nested_example.Employee'),
        ),
    ]
