# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        types: [ python ]
        language: python
        stages: [ push, commit ]

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        types: [ python ]
        language: python
        stages: [ push, commit ]
